name: Deploy to Fargate

on:
  workflow_run:
    workflows: ["Push Docker images to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster user-auth-cluster \
            --service user-auth-task-service-pylwyhdu \
            --force-new-deployment \
            --region us-east-1